pipeline:
  identifier: Build_circleci_demo_ruby_rails_1689101327051
  name: Build circleci-demo-ruby-rails
  orgIdentifier: default
  projectIdentifier: sandbox
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Jim_Sheldon
        repoName: jimsheldon/circleci-demo-ruby-rails
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: bundleinstall
                  name: bundle_install
                  spec:
                    command: bundle install — jobs=3 — retry=3
                  timeout: ""
                  type: Run
              - step:
                  identifier: bundledbcreate
                  name: bundle_db_create
                  spec:
                    command: bundle exec rake db:create
                  timeout: ""
                  type: Run
              - step:
                  identifier: bundledbmigrate
                  name: bundle_db_migrate
                  spec:
                    command: bundle exec rake db:migrate
                  timeout: ""
                  type: Run
              - step:
                  identifier: bundlerspec
                  name: bundle_rspec
                  spec:
                    command: bundle exec rspec
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
