pipeline:
  identifier: Build_circleci_demo_ruby_rails_1689101327051
  name: Build circleci-demo-ruby-rails
  orgIdentifier: default
  projectIdentifier: sandbox
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Jim_Sheldon
        repoName: jimsheldon/circleci-demo-ruby-rails
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdeps
                  name: install_deps
                  spec:
                    command: |-
                      bundle config deployment 'true'
                      bundle config gemfile "Gemfile"
                      bundle config path "./vendor/bundle"
                      bundle check || bundle install
                  timeout: ""
                  type: Run
              - step:
                  identifier: installpackages
                  name: install_packages
                  spec:
                    command: yarn install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        identifier: test
        name: test
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  envVariables:
                    BUNDLE_JOBS: "3"
                    BUNDLE_RETRY: "3"
                    PGHOST: 127.0.0.1
                    PGPASSWORD: ""
                    PGUSER: circleci-demo-ruby
                    RAILS_ENV: test
                  identifier: background
                  name: background
                  spec:
                    envVariables:
                      POSTGRES_DB: rails_blog_test
                      POSTGRES_PASSWORD: ""
                      POSTGRES_USER: circleci-demo-ruby
                    image: circleci/postgres:9.5-alpine
                  timeout: ""
                  type: Background
              - step:
                  envVariables:
                    BUNDLE_JOBS: "3"
                    BUNDLE_RETRY: "3"
                    PGHOST: 127.0.0.1
                    PGPASSWORD: ""
                    PGUSER: circleci-demo-ruby
                    RAILS_ENV: test
                  identifier: installdeps1
                  name: install_deps
                  spec:
                    command: |-
                      bundle config deployment 'true'
                      bundle config gemfile "Gemfile"
                      bundle config path "./vendor/bundle"
                      bundle check || bundle install
                  timeout: ""
                  type: Run
              - step:
                  envVariables:
                    BUNDLE_JOBS: "3"
                    BUNDLE_RETRY: "3"
                    PGHOST: 127.0.0.1
                    PGPASSWORD: ""
                    PGUSER: circleci-demo-ruby
                    RAILS_ENV: test
                  identifier: installpackages1
                  name: install_packages
                  spec:
                    command: yarn install
                  timeout: ""
                  type: Run
              - step:
                  envVariables:
                    BUNDLE_JOBS: "3"
                    BUNDLE_RETRY: "3"
                    PGHOST: 127.0.0.1
                    PGPASSWORD: ""
                    PGUSER: circleci-demo-ruby
                    RAILS_ENV: test
                  identifier: waitfordb
                  name: Wait for DB
                  spec:
                    command: |-
                      set -eo pipefail
                      dockerize -wait tcp://localhost:5432 -timeout 1m
                    image: cimg/ruby:2.7-node
                    shell: Bash
                  timeout: ""
                  type: Run
              - step:
                  envVariables:
                    BUNDLE_JOBS: "3"
                    BUNDLE_RETRY: "3"
                    PGHOST: 127.0.0.1
                    PGPASSWORD: ""
                    PGUSER: circleci-demo-ruby
                    RAILS_ENV: test
                  identifier: databasesetup
                  name: Database setup
                  spec:
                    command: |-
                      set -eo pipefail
                      bundle exec rails db:schema:load --trace
                    image: cimg/ruby:2.7-node
                    shell: Bash
                  timeout: ""
                  type: Run
              - step:
                  envVariables:
                    BUNDLE_JOBS: "3"
                    BUNDLE_RETRY: "3"
                    PGHOST: 127.0.0.1
                    PGPASSWORD: ""
                    PGUSER: circleci-demo-ruby
                    RAILS_ENV: test
                  identifier: rspectest
                  name: rspec_test
                  spec:
                    command: |-
                      mkdir -p "/tmp/test-results/rspec"
                      bundle exec rspec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
                  timeout: ""
                  type: Run
              - step:
                  envVariables:
                    BUNDLE_JOBS: "3"
                    BUNDLE_RETRY: "3"
                    PGHOST: 127.0.0.1
                    PGPASSWORD: ""
                    PGUSER: circleci-demo-ruby
                    RAILS_ENV: test
                  identifier: rubocopcheck
                  name: rubocop_check
                  spec:
                    shell: Sh
                    command: |-
                      mkdir -p "/tmp/rubocop-results"
                      bundle exec rubocop . --out /tmp/rubocop-results/check-results.xml --format progress
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
